### ISSUE TITLE
Problems when comparing hash/arrays

### ISSUE THREAD

**Issue by ambs** [TLINDEN/Data-Validate-Struct#4] opened 2023-02-04 11:03 UTC
Consider a reference schema:

```perl
{ foo => [{bar => 'int'}]}
```

If you try to compare with

```perl
{ foo => {bar => 'int'}}
```

the module will die, given it will try to apply array derreferencing on top of a hash.

PR #3 fixes this behavior.

**Comment by ambs** [comment] 2023-02-08 21:56
@TLINDEN do not want to push, but it would easy my life to have this fix on a release soon. Thanks!

**Comment by TLINDEN** [comment] 2023-03-08 13:36
Howdy,

I had to revert that change, see https://github.com/TLINDEN/Data-Validate-Struct/issues/7. The problem was, that it did not validate optional elements anymore, which broke production code.

Also I did not look carefully enough at your proposal. The problem is, that your use case is wrong:

```
{ foo => [{bar => 'int'}]}  != { foo => {bar => 'int'}}
```

The reference is a key pointing to an array of hashes while the supplied data structure contains a key pointing to a hash. That's not the same thing and shall not validate to true.

**Comment by ambs** [comment] 2023-03-08 14:45
Hi
Yes, they are different. But the module should not die, just return a false value.
That's what I mention in the ticket above :-)

Can you add a test case for the optional elements, so that I can try to rework my patch?
Thanks

**Comment by TLINDEN** [comment] 2023-03-08 16:57
Yes there's a test case for this now.

**Comment by ambs** [comment] 2023-03-11 16:18
Howdy,
Here goes a new patch.
I didn't know that Perl allows you to derreference undefined values without warnings.
Cheers

**Comment by TLINDEN** [comment] 2023-03-22 11:57
Merged the new PR, looks good to me now. Thanks a lot for the work!

**Closed by TLINDEN** 2023-03-22 11:57 UTC
Labels: bug
